schooldriver/django_sis/urls.py
from django.conf.urls import include, patterns, url
from ecwsp.sis import views as sis_views
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from api.routers import api_urls
from responsive_dashboard import views as dashboard_views
from ecwsp.sis.views import AttendanceReportView
from django.http import HttpResponse

dajaxice_autodiscover()
admin.autodiscover()
admin.site.login = login_required(admin.site.login)

def robots(request):
    ''' Try to prevent search engines from indexing
    uploaded media. Make sure your web server is
    configured to deny directory listings. '''
    return HttpResponse(
        'User-agent: *\r\nDisallow: /media/\r\n',
        content_type='text/plain'
    )

urlpatterns = patterns('',
    (r'^robots.txt', robots),
    (r'^admin/', include("massadmin.urls")),
    (r'^admin_export/', include("admin_export.urls")),
    (r'^ckeditor/', include('ecwsp.ckeditor_urls')),#include('ckeditor.urls')),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^$', 'ecwsp.sis.views.index'),
    (r'^sis/', include('ecwsp.sis.urls')),
    (r'^admin/jsi18n', 'django.views.i18n.javascript_catalog'),

    (r'^report_builder/', include('report_builder.urls')),
    (r'^simple_import/', include('simple_import.urls')),
    url(r'^accounts/password_change/$', 'django.contrib.auth.views.password_change'),
    url(r'^accounts/password_change_done/$', 'django.contrib.auth.views.password_change_done', name="password_change_done"),

    (r'^logout/$', sis_views.logout_view),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'),
    (r'^admin/', include(admin.site.urls) ),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(dajaxice_config.dajaxice_url, include('ecwsp.dajaxice_urls')),
    (r'^reports/(?P<name>attendance_report)/$', AttendanceReportView.as_view()),
    (r'^reports/', include('scaffold_report.urls')),
    url(r'^impersonate/', include('impersonate.urls')),
    url(r'^api/', include(api_urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

if settings.GAPPS:
    urlpatterns += patterns('', (r'^accounts/login/$', 'google_auth.views.login'), )
else:
    urlpatterns += patterns('', (r'^accounts/login/$', 'django.contrib.auth.views.login'), )

if 'ldap_groups' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',(r'^ldap_grp/', include('ldap_groups.urls')),)
if 'ecwsp.discipline' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^discipline/', include('ecwsp.discipline.urls')), )
if 'ecwsp.attendance' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^attendance/', include('ecwsp.attendance.urls')), )
if 'ecwsp.schedule' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^schedule/', include('ecwsp.schedule.urls')), )
    # Course is a nicer looking url
    urlpatterns += patterns('', (r'^course/', include('ecwsp.schedule.urls')), )
if 'ecwsp.grades' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^grades/', include('ecwsp.grades.urls')), )
    urlpatterns += patterns('', (r'^course/', include('ecwsp.grades.urls')), )
if 'ecwsp.work_study' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^work_study/', include('ecwsp.work_study.urls')), )
if 'ecwsp.admissions' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^admissions/', include('ecwsp.admissions.urls')), )
if 'ecwsp.volunteer_track' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^volunteer_track/', include('ecwsp.volunteer_track.urls')), )
if 'ecwsp.benchmark_grade' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^benchmark_grade/', include('ecwsp.benchmark_grade.urls')), )
if 'ecwsp.inventory' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^inventory/', include('ecwsp.inventory.urls')), )
if 'ecwsp.engrade_sync' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^engrade_sync/', include('ecwsp.engrade_sync.urls')), )
if 'ecwsp.naviance_sso' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^naviance_sso/', include('ecwsp.naviance_sso.urls')), )
if 'ecwsp.alumni' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^alumni/', include('ecwsp.alumni.urls')), )
if 'ecwsp.counseling' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^counseling/', include('ecwsp.counseling.urls')), )
if 'ecwsp.integrations.canvas_sync' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^canvas_sync/', include('ecwsp.integrations.canvas_sync.urls')), )
if 'ecwsp.integrations.schoolreach' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^schoolreach/', include('ecwsp.integrations.schoolreach.urls')), )
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )
if 'social.apps.django_app.default' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', url('', include('social.apps.django_app.urls', namespace='social')),)
if 'file_import' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',(r'^file_import/', include('file_import.urls')),)

urlpatterns += patterns('', (r'^administration/', include('ecwsp.administration.urls')), )
urlpatterns += patterns('', (r'^', include('responsive_dashboard.urls')), )

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,})
    )

schooldriver/ecwsp/work_study/urls.py
from django.conf.urls import *
from ecwsp.work_study import views
from responsive_dashboard.views import generate_dashboard

urlpatterns = patterns('',
    (r'^$', generate_dashboard, {'app_name': 'work_study'}),
    (r'^reports/$', views.report_builder_view),
    (r'^student_timesheet/$', views.student_timesheet),
    (r'^supervisor/create_timesheet/(?P<studentId>\d+)/$', views.create_time_card),
    (r'^supervisor/change_supervisor/(?P<studentId>\d+)/$', views.change_supervisor),
    (r'^supervisor/$', views.supervisor_dash),
    (r'^supervisor/view/$', views.supervisor_view),
    (r'^supervisor/view/xls/$', views.supervisor_xls),
    (r'^student/view/$', views.student_view),
    (r'^student/edit/(?P<tsid>\d+)/$', views.student_edit),
    (r'^approve/$', views.approve),
    (r'^supervisor/delete/$', views.timesheet_delete),
    (r'^dol/$',views.dol_form),
    (r'^dol/(?P<id>\d+)$', views.dol_form),
    (r'^student_meeting/$', views.student_meeting),
    (r'^company_contract/(?P<id>\d+)/$', views.company_contract1),
    (r'^company_contract2/(?P<id>\d+)/$', views.company_contract2),
    (r'^company_contract3/(?P<id>\d+)/$', views.company_contract3),
    (r'^company_contract_complete/(?P<id>\d+)/$', views.company_contract_complete),
    (r'^company_contract_pdf/(?P<id>\d+)/$', views.company_contract_pdf),
    (r'^fte_chart/$', views.fte_chart),
    (r'^routes/$', views.routes),
    (r'^take_attendance/$', views.take_attendance),
    (r'^take_attendance/(?P<work_day>\d+)/$', views.take_attendance),
)

schooldriver/ecwsp/work_study/forms.py
from ecwsp.work_study.models import (StudentWorker, TimeSheet, Contact,
        TimeSheetPerformanceChoice, ClientVisit, WorkTeam, CompContract,
        Attendance)
from ecwsp.sis.forms import StudentReportWriterForm
from ecwsp.administration.models import Configuration

from django import forms
from django.contrib.admin import widgets as adminwidgets
from django.db.utils import ProgrammingError
from django.utils.safestring import mark_safe
from django.utils.encoding import force_unicode
from django.utils.html import conditional_escape

from django.conf import settings
from constance import config

import autocomplete_light
from decimal import Decimal
from datetime import datetime, date
from itertools import chain


class CustomCheckboxSelectMultiple(forms.CheckboxSelectMultiple):
    items_per_row = 2 # Number of items per row

    def render(self, name, value, attrs=None, choices=()):
        if value is None: value = []
        has_id = attrs and 'id' in attrs
        final_attrs = self.build_attrs(attrs, name=name)
        output = ['<table  style="width:99%;"><tr>']
        # Normalize to strings
        str_values = set([force_unicode(v) for v in value])
        for i, (option_value, option_label) in enumerate(chain(self.choices, choices)):
            # If an ID attribute was given, add a numeric index as a suffix,
            # so that the checkboxes don't all have the same ID attribute.
            if has_id:
                final_attrs = dict(final_attrs, id='%s_%s' % (attrs['id'], i))
                label_for = ' for="%s"' % final_attrs['id']
            else:
                label_for = ''

            cb = forms.CheckboxInput(final_attrs, check_test=lambda value: value in str_values)
            option_value = force_unicode(option_value)
            rendered_cb = cb.render(name, option_value)
            option_label = conditional_escape(force_unicode(option_label))
            if i != 0 and i % self.items_per_row == 0:
                output.append('</tr><tr>')
            output.append('<td nowrap><label%s>%s %s</label></td>' % (label_for, rendered_cb, option_label))
        output.append('</tr></table>')
        return mark_safe('\n'.join(output))



class HorizRadioRenderer(forms.RadioSelect.renderer):
    """ this overrides widget method to put radio buttons horizontally
        instead of vertically.
    """
    def render(self):
        """Outputs radios"""
        return mark_safe(u'\n'.join([u' %s&nbsp;&nbsp; \n ' % w for w in self]))


class TdRadioRenderer(forms.RadioSelect.renderer):
    """
    this overrides widget method to put radio buttons in td's
    """
    def render(self):
        """Outputs radios"""
        #return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))
        return mark_safe(u'\n'.join([u'<td class="border " style="padding"> %s </td>\n' % w for w in self]))

class TdNoTextRadioRenderer(forms.RadioSelect.renderer):
    """
    this overrides widget method to put radio buttons in td's
    """
    def render(self):
        """Outputs radios"""
        #return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))
        return mark_safe(u'\n'.join([u'<td class="none nofont" style="font-size: 0px !important; padding-left:10px; padding-right:10px;"> <span style="font-size: 0px;">%s</span> </td>\n' % w for w in self]))


class TimeSheetForm(forms.ModelForm):
    class Meta:
        model = TimeSheet

    my_supervisor = forms.ModelChoiceField(queryset=Contact.objects.all(), required=False)
    date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, validators=settings.DATE_VALIDATORS)
    time_in = forms.TimeField()
    time_lunch = forms.TimeField()
    time_lunch_return = forms.TimeField()
    time_out = forms.TimeField()
    performance = forms.ModelChoiceField(queryset=TimeSheetPerformanceChoice.objects.all(),required=False,widget=forms.Select(attrs={'class':'timecard-performance'}))
    edit = forms.BooleanField(required=False)

    def set_supers(self, qs):
        self.fields["my_supervisor"].queryset = qs

    def clean(self):
        cleaned_data = self.cleaned_data
        time_in = cleaned_data.get("time_in")
        time_lunch = cleaned_data.get("time_lunch")
        time_lunch_return = cleaned_data.get("time_lunch_return")
        time_out = cleaned_data.get("time_out")

        # validate max hours
        try:
            hours = time_lunch.hour - time_in.hour
            mins = time_lunch.minute - time_in.minute
            hours += time_out.hour - time_lunch_return.hour
            mins += time_out.minute - time_lunch_return.minute
            hours += mins/Decimal(60)
        except:
            raise forms.ValidationError("You must fill out time in and time out.")
        if hours > config.WORK_STUDY_MAX_HOURS_DAY:
            raise forms.ValidationError("Only " + unicode(config.WORK_STUDY_MAX_HOURS_DAY) + " hours are allowed in one day.")
        elif hours <= 0:
            raise forms.ValidationError("You cannot have negative hours!")


        # validate time in and out
        if time_lunch_return < time_lunch:
            raise forms.ValidationError("Cannot return from lunch before leaving for lunch.")
        if time_in > time_out:
            raise forms.ValidationError("Cannot leave before starting. Check your times.")

        #Don't allow two in the same day.
        ts = TimeSheet.objects.filter(date=cleaned_data.get('date'), student=cleaned_data.get('student'))

        if ts.count() > 0 and not cleaned_data.get('edit'):
            conf, created = Configuration.objects.get_or_create(name="Allow multiple time sheets in one day")
            if created:
                conf.help_text = "True\nFalse"
                conf.save()
            if conf.value == "False":
                txt = "Cannot submit two time sheets in one day.\n Please edit an existings time sheet if you've" + \
                    " made a mistake. Approved time sheets may only be edited by a supervisor or cwsp staff."
                raise forms.ValidationError(txt)
        # Always return the full collection of cleaned data.
        return cleaned_data

class ChangeSupervisorForm(forms.ModelForm):
    class Meta:
        model = StudentWorker
        fields = ('primary_contact',)

    def __init__(self, *args, **kwargs):
        comp = kwargs.pop('company')
        super(ChangeSupervisorForm, self).__init__(*args, **kwargs)
        self.fields["primary_contact"].queryset = Contact.objects.filter(workteam=comp)


class AddSupervisor(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('fname', 'lname', 'phone', 'phone_cell', 'email',)

class ReportBuilderForm(forms.Form):
    custom_billing_begin = forms.DateField(widget=adminwidgets.AdminDateWidget(), required=False, validators=settings.DATE_VALIDATORS)
    custom_billing_end = forms.DateField(widget=adminwidgets.AdminDateWidget(), required=False, validators=settings.DATE_VALIDATORS)

class ReportTemplateForm(StudentReportWriterForm):
    date_begin = None
    date_end = None
    try:
        student = autocomplete_light.MultipleChoiceField('StudentUserAutocomplete', required=False)
    except ProgrammingError:
        pass

    def clean(self):
        data = self.cleaned_data
        if not data.get('student') and not data.get('all_students'):
            raise forms.ValidationError("You must either check \"all students\" or select a student")
        if not data.get('template') and not data.get('upload_template'):
            raise forms.ValidationError("You must either select a template or upload one.")
        return data

class DolForm(forms.ModelForm):
    class Meta:
        model = ClientVisit
        widgets = {
            'date': adminwidgets.AdminDateWidget(),
            'work_environment': forms.RadioSelect(renderer=HorizRadioRenderer),
            'attendance_and_punctuality': forms.RadioSelect(renderer=TdNoTextRadioRenderer),
            'attitude_and_motivation': forms.RadioSelect(renderer=TdNoTextRadioRenderer),
            'productivity_and_time_management': forms.RadioSelect(renderer=TdNoTextRadioRenderer),
            'ability_to_learn_new_tasks': forms.RadioSelect(renderer=TdNoTextRadioRenderer),
            'professional_appearance': forms.RadioSelect(renderer=TdNoTextRadioRenderer),
            'interaction_with_coworkers': forms.RadioSelect(renderer=TdNoTextRadioRenderer),
            'initiative_and_self_direction': forms.RadioSelect(renderer=TdNoTextRadioRenderer),
            'accuracy_and_attention_to_detail': forms.RadioSelect(renderer=TdNoTextRadioRenderer),
            'organizational_skills': forms.RadioSelect(renderer=TdNoTextRadioRenderer),
        }
    dol = forms.BooleanField(initial=True, required=False, widget=forms.CheckboxInput(attrs={'style':'visibility: hidden;'}))

    def save(self, *args, **kwargs):
        commit = kwargs.pop('commit', True)
        instance = super(DolForm, self).save(*args, commit = False, **kwargs)
        instance.dol = True
        if commit:
            instance.save()
        return instance

class StudentWorkerBulkChangeForm(forms.Form):
    day = forms.ChoiceField(choices=[['','----']]+StudentWorker.dayOfWeek, required=False)
    placement = forms.ModelChoiceField(queryset=WorkTeam.objects.all(), required=False)
    clear_placement = forms.BooleanField(help_text="Set placement to None", required=False)
    school_pay_rate = forms.DecimalField(max_digits=5, decimal_places=2, required=False)
    student_pay_rate = forms.DecimalField(max_digits=5, decimal_places=2, required=False)

# Django form wizard sucks, not using it
class CompanyContactForm1(forms.ModelForm):
    class Meta:
        model = CompContract
        fields = ('company', 'company_name', 'name', 'title', 'date', 'number_students')
        widgets = {
           'company': forms.HiddenInput(),
        }
    company_name = forms.CharField(max_length=255)
    name = forms.CharField(max_length=255)
    title = forms.CharField(max_length=255)

schooldriver/ecwsp/work_study/templates/work_study/company_contract1.html
{% extends "base.html" %}

{% block css %}
	textarea {
		width:100%;
		height:70px;
	}
	input[type=text] {
		width:300px;
	}
{% endblock %}

{% block content %}
	<h1 style="text-align:center;"> Contract for {{ company }} </h1>
	<br/>
	<div class="contract">
		<form action="" method="post">
			{{ form.non_field_errors }}
			<table>
				{{ form.company }}
				<tr><th>{{ form.company_name.label }}:</th>
					<td>{{ form.company_name }} {{ form.company_name.errors }}</td></tr>
				<tr><th>{{ form.name.label }}:</th>
					<td>{{ form.name }} {{ form.name.errors }}</td></tr>
				<tr><th>{{ form.title.label }}:</th>
					<td>{{ form.title }} {{ form.title.errors }}</td></tr>
				<tr><th>{{ form.date.label }}:</th>
					<td>{{ form.date }} {{ form.date.errors }}</td></tr>
				<tr><th>{{ form.number_students.label }}:</th>
					<td>{{ form.number_students }} {{ form.number_students.errors }}</td></tr>
			</table>
			<input type="submit" value="Next" style="width:150px;"/>
		</form>
	</div>
{% endblock %}

schooldriver/ecwsp/work_study/templates/work_study/student_timesheet.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load widget_tweaks %}

{% block extrahead %}    
    <script type="text/javascript" src="{% static "js/jquery.ptTimeSelect.js" %}"></script>    
    <script type="text/javascript" src="{% static "js/date.js" %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static "css/ui.core.css" %}" media="screen">
    <link rel="stylesheet" type="text/css" href="{% static "css/jquery.ptTimeSelect.css" %}">
    
    <script type="text/javascript">
    // Wow dates in javascript are soooooo bad
        function add_hours(){
            try {
                var time_in = Date.parse($('#id_time_in').val())
                var hours_in = time_in.getHours();
                var minutes_in = time_in.getMinutes();
                
                var time_out = Date.parse($('#id_time_out').val())
                var hours_out = time_out.getHours();
                var minutes_out = time_out.getMinutes();
                
                var time_lunch = Date.parse($('#id_time_lunch').val())
                var time_lunch_return = Date.parse($('#id_time_lunch_return').val())
                if (time_lunch && time_lunch_return) {
                    var hours_lunch = time_lunch.getHours();
                    var minutes_lunch = time_lunch.getMinutes();
                    var hours_lunch_return = time_lunch_return.getHours();
                    var minutes_lunch_return = time_lunch_return.getMinutes();
                } else {
                    var hours_lunch = 0;
                    var minutes_lunch = 0;
                    var hours_lunch_return = 0;
                    var minutes_lunch_return = 0;
                }
                
                var hours = hours_lunch - hours_in;
                hours = hours + (hours_out - hours_lunch_return);
                
                var minutes = minutes_lunch - minutes_in;
                minutes = minutes + (minutes_out - minutes_lunch_return);
                
                hours = hours + minutes/60;
                hours = Math.round(hours * 100) / 100
                
                $('#span_hours').html(hours);
            } catch (err) {
                $('#span_hours').html("N/A");
            }
            
        }
        
        $(document).ready(
            function () {
                $('code').each(
                    function() {
                        eval($(this).html());
                    }
                )
                add_hours();
                $('#ptTimeSelectSetButton').click(function() {
                    add_hours();
                });
                $('#id_time_in').change(function() {
                    add_hours();
                });
                $('#id_time_out').change(function() {
                    add_hours();
                });
                $('#id_time_lunch').change(function() {
                    add_hours();
                });
                $('#id_time_lunch_return').change(function() {
                    add_hours();
                });
                $(".datepicker").datepicker();
            }
        );
        
        function check_time() {
            lunch_out = document.timesheet_form.time_lunch.value;
            lunch_in = document.timesheet_form.time_lunch_return.value;
            if (lunch_out == "" && lunch_in == "") {
                document.timesheet_form.time_lunch.value = "12:00 pm";
                document.timesheet_form.time_lunch_return.value = "12:00 pm";
            }
            return check_date();
        }
        
        function no_lunch() {
            document.timesheet_form.time_lunch.value = "";
            document.timesheet_form.time_lunch_return.value = "";
            add_hours();
        }
        
        function check_date() {
            date = new Date(document.timesheet_form.date.value.replace('-', '/').replace('-', '/'));
            if (date.getDay()%6==0) {
                if (confirm('Warning: You have selected a weekend.')) {
                    return true;
                } else {
                    return false;
                } 
            }
            return true;
        }
    </script>
{% endblock %}

{% block content %}

<div class="row">
<h1>Create Time Card</h1>

<div class="subhead-text">
You are logged in as
<strong>
    {% if user.first_name and user.last_name %}
        {{ user.first_name }} {{ user.last_name }}
    {% else %}
        {{ user }}
    {% endif %}
</strong>
.
{% if student %}
    Please fill out your time card below.
{% else %}
    Please review {{ studentName.fname }} {{ studentName.lname }}'s time card below.
{% endif %}
</div>

{{ form.non_field_errors }}
{% if warning %}
    <br/><h3 style="color: red;">Warning student has already posted a time sheet for today. You may approve it <a href="{% url "ecwsp.work_study.views.approve" %}?key={{ key }}">here</a></h3><br/>
{% endif %}
</div>

<form method="post" name="timesheet_form" onsubmit="return check_time()" action="">

<table class="timecard-date">
<tbody>
    <tr>
        <td>Date</td>
    </tr>
    <tr>
        <td>
            <input
                   type="text"
                   class="timecard-datefield datepicker"
                   name="{{ form.date.html_name }}"
                   id="id_{{ form.date.html_name }}"
                   value="{{ form.date.value }}"/>
        </td>
        {{ form.date.errors }}
    </tr>
</tbody>
</table>

<table class="timecard-date">
<tbody>
	<tr>
		<td>Start</td>
		<td>Lunch Out</td>
		<td>Lunch In</td>
		<td>End</td>
		<td></td>
	</tr>
	<tr>
		<td>{{ form.time_in|add_class:"timecard-datefield" }} {{ form.time_in.errors }}</td>
		<td>{{ form.time_lunch|add_class:"timecard-datefield" }} {{ form.time_lunch.errors }}</td>
		<td>{{ form.time_lunch_return|add_class:"timecard-datefield" }} {{ form.time_lunch_return.errors }}</td>
		<td>{{ form.time_out|add_class:"timecard-datefield" }} {{ form.time_out.errors }}</td>
		<td><a href="#" onclick="no_lunch()" class="button gray">No Lunch</a></td>
                            <script>
                            $(document).ready(function(){
                                $('#id_time_in').ptTimeSelect();
                                $('#id_time_lunch').ptTimeSelect();
                                $('#id_time_lunch_return').ptTimeSelect();
                                $('#id_time_out').ptTimeSelect();
                            });
                            </script>
	</tr>
</tbody>
</table>

<div class="subhead-text">
{% if student %} You {% else %} {{ studentName.fname }} {{ studentName.lname }} {% endif %} worked <strong><span id="span_hours"></span></strong> total hours.
</div>


<div class="timecard-comments">
<p>
    {% if student %} My supervisor was: {% else %} Supervisor: {% endif %}
		{{ form.my_supervisor }} {{ form.my_supervisor.errors }}
</p>
</div>


<div class="spacer-3"></div>


<div class="timecard-options">
{% if not form.for_pay.is_hidden %}
    <input type="checkbox" name="{{ form.for_pay.html_name }}" id="id_{{ form.for_pay.html_name }}" {% if form.for_pay.value %}checked="checked"{% endif %}>
        {% if student %} I {% else %} Student {% endif %}was working over a school break (such as a holiday) and should be paid separately for these hours.
    </label><br />
    {{ form.for_pay.errors }} 
{% endif %}
<input type="checkbox" name="{{ form.make_up.html_name }}" id="id_{{ form.make_up.html_name }}" {% if form.make_up.value %}checked="checked"{% endif %}>
    {% if student %} I {% else %} Student {% endif %} was making up a missed day.
</label>
</div>

<div class="spacer-3"></div>

<div class="timecard-comments">

	<p>{% if student %} My {% else %} Student's {% endif %} major accomplishment for today was...</p>
        <textarea
                  class="timecard-commentsbox"
                  id="id_{{ form.student_accomplishment.html_name }}"
                  name="{{ form.student_accomplishment.html_name }}">{{ form.student_accomplishment.value|default_if_none:"" }}</textarea>
        {{ form.student_accomplishment.errors }} 
	
	<p>Client comments, concerns, questions...</p>
        {% if student %}
            <textarea class="timecard-commentsbox" disabled="disabled"></textarea>
        {% else %}
            <textarea
                    class="timecard-commentsbox"
                    id="id_{{ form.supervisor_comment.html_name }}"
                    name="{{ form.supervisor_comment.html_name }}">{{ form.supervisor_comment.value|default_if_none:"" }}</textarea>
            {{ form.supervisor_comment.errors }}
            <br/>
            {{ form.show_student_comments }} Allow students to see comments and performance review.
        {% endif %}

	<p>Daily Student Worker Performance:
		 {{ form.performance.errors }} {{ form.performance }} 
	</p>

{% if approved %}
    <p> Approved by supervisor </p>
{% endif %}    
{% if not student %}
    <p> Submitted by student </p>
{% endif %}
</div>




<div class="spacer-3"></div>


<div class="submitwrap">
{% if student %}
    <input type="submit" class="button gray" value="Submit for Approval">
{% else %}
    <input type="submit" class="button gray" value="Approve Time Card"/>
{% endif %}
<span class="hidden">{{ form.student }} {{ form.company }} {{ form.edit }}</span>
</div>
</form>
{% endblock %}